# Generated by Django 3.2.8 on 2021-11-19 20:54
import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0003_auto_20211119_0845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareableLink',
        ),
        migrations.AddField(
            model_name='match',
            name='code',
            field=models.CharField(default=api.models.generate_code, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='match',
            name='host',
            field=models.CharField(default='Host', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createdby',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
