# Generated by Django 3.2.8 on 2021-12-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0006_artist_belongsto_bracket_createdby_item_match_playlist_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('vote', models.IntegerField()),
                ('song_name', models.CharField(max_length=100)),
            ],
        ),
    ]
