# Generated by Django 3.2.8 on 2021-12-09 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0011_alter_roomvotes_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomvotes',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brackets.votes'),
        ),
    ]
