# Generated by Django 3.2.8 on 2021-12-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0012_alter_roomvotes_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='user',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RoomVotes',
        ),
    ]
