# Generated by Django 3.2.8 on 2021-12-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0014_auto_20211220_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='room_code',
            field=models.CharField(default='ABCDEF', max_length=6),
        ),
    ]
