# Generated by Django 3.2.8 on 2021-12-23 21:15

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('code', models.CharField(default=api.models.generate_code, max_length=6, unique=True)),
                ('host', models.CharField(default=None, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('bracket_type', models.CharField(default='single_elim', max_length=20)),
                ('song_type', models.CharField(default='Artist', max_length=10)),
                ('artist', models.CharField(default='None', max_length=60)),
                ('playlist', models.CharField(default='None', max_length=60)),
                ('max_users', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=40)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lobby')),
            ],
        ),
    ]
