# Generated by Django 3.2.8 on 2021-11-20 16:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_code, max_length=8, unique=True)),
                ('host', models.CharField(default=None, max_length=50, unique=True)),
                ('bracket_type', models.CharField(default='single_elim', max_length=20)),
                ('artist', models.CharField(default='None', max_length=60)),
                ('max_users', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='max_users',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
