# Generated by Django 3.2.8 on 2021-11-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211120_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='code',
        ),
        migrations.RemoveField(
            model_name='match',
            name='host',
        ),
        migrations.RemoveField(
            model_name='match',
            name='max_users',
        ),
    ]
