# Generated by Django 3.2.8 on 2021-12-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='playlist',
            field=models.CharField(default='None', max_length=60),
        ),
        migrations.AddField(
            model_name='lobby',
            name='song_type',
            field=models.CharField(default='Artist', max_length=10),
        ),
    ]
