# Generated by Django 3.2.8 on 2021-12-21 01:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211218_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='code',
            field=models.CharField(default=api.models.generate_code, max_length=6, unique=True),
        ),
    ]
